name: moviestash
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^6.0.0
  get_it: ^7.6.4
  go_router: ^12.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  retrofit: ^4.0.3
  share_plus: ^7.2.1
  shimmer: ^3.0.0
  
  
dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
  retrofit_generator: ^8.0.4
  very_good_analysis: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - .env


